basePath: '{{.BasePath}}'
definitions:
  common.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: An example of gin
  license:
    name: MIT
    url: https://github.com/fanhengyuan/gin-test/blob/master/LICENSE
  termsOfService: https://github.com/fanhengyuan/gin-test
  title: Gin Web Test
  version: "1.0"
paths:
  /test/font:
    get:
      consumes:
      - application/json
      parameters:
      - description: base64 string
        in: query
        name: base64
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Response'
            type: object
      summary: Base64 Decode
      tags:
      - Test
  /test/ping:
    get:
      consumes:
      - application/json
      description: Test Ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
            type: object
      summary: Ping
      tags:
      - Test
swagger: "2.0"
